config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :olds
  resources :cars
  resources :new_cars
  get 'home/index'
  devise_for :users
  root 'home#index'
  get 'gallery/index'
  get 'gallery/checkout'
  post 'gallery/checkout'
  get 'gallery/purchase_complete'
  get 'gallery/random'
  post 'gallery/search'
  get 'gallery/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/old.rb
class Old < ApplicationRecord
  has_one_attached :image
end

app/controllers/olds_controller.rb
class OldsController < ApplicationController
  before_action :set_old, only: %i[ show edit update destroy ]

  # GET /olds or /olds.json
  def index
    @olds = Old.all
  end

  # GET /olds/1 or /olds/1.json
  def show
  end

  # GET /olds/new
  def new
    @old = Old.new
  end

  # GET /olds/1/edit
  def edit
  end

  # POST /olds or /olds.json
  def create
    @old = Old.new(old_params)

    respond_to do |format|
      if @old.save
        format.html { redirect_to @old, notice: "Old was successfully created." }
        format.json { render :show, status: :created, location: @old }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @old.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /olds/1 or /olds/1.json
  def update
    respond_to do |format|
      if @old.update(old_params)
        format.html { redirect_to @old, notice: "Old was successfully updated." }
        format.json { render :show, status: :ok, location: @old }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @old.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /olds/1 or /olds/1.json
  def destroy
    @old.destroy
    respond_to do |format|
      format.html { redirect_to olds_url, notice: "Old was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_old
      @old = Old.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def old_params
      params.require(:old).permit(:name, :company, :price, :modal, :seat, :owner, :desc,:image)
    end
end

app/helpers/olds_helper.rb
module OldsHelper
end

app/views/olds/_form.html.erb
<%= form_with(model: old, local: true) do |form| %>
  <% if old.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(old.errors.count, "error") %> prohibited this old from being saved:</h2>

      <ul>
      <% old.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :modal %>
    <%= form.number_field :modal %>
  </div>

  <div class="field">
    <%= form.label :seat %>
    <%= form.number_field :seat %>
  </div>

  <div class="field">
    <%= form.label :owner %>
    <%= form.number_field :owner %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/olds/edit.html.erb
<h1>Editing Old</h1>

<%= render 'form', old: @old %>

<%= link_to 'Show', @old %> |
<%= link_to 'Back', olds_path %>

app/views/olds/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <style>
      .bg-cover {
          background-size: cover !important;
      }


      .body1 {
          min-height: 100vh;
      }
      body {
          background: #f4f4f4;
      }

      .banner {
          background: #a770ef;
          background: -webkit-linear-gradient(to right, #a770ef, #cf8bf3, #fdb99b);
          background: linear-gradient(to right, #a770ef, #cf8bf3, #fdb99b);
      }
  </style>
  <title>Autotrader</title>
  <link rel="shortcut icon" href="m1.jpg" width="1000px">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>
<body class="body1">
  <div style="background: url(<%= asset_path 'a.jpg' %>);" class="jumbotron bg-cover text-white" >
  <div class="container py-5 text-center">
    <h1 class="display-4 font-weight-bold">Used cars for sell</h1>
    <p class="font-italic mb-0">Used car for sell</p>
    <p class="font-italic">made by
      <a href="#" class="text-white">
        <u>Autotrader</u>
      </a>
    </p>
  </div>
</div>
</body>
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <div class="px-lg-5">
    <div class="row">
      <% @olds.each do |old| %>
      <!-- Gallery item -->
      <div class="col-xl-3 col-lg-4 col-md-6 mb-4">
        <div class="bg-white rounded shadow-sm"><img src="image411.jpg" alt="" class="img-fluid card-img-top">
          <div class="p-4">
            <h5> <a href="#" class="text-dark">Used <%= old.modal %> <%= old.company %> <%= old.name %></a></h5>
            <h8 class="font-weight-bold my-2">$ <%= old.price %></h8>
            <p class="small text-muted mb-0"><%= old.desc %></p><br>
            <div class="container-fluid">
              <div class="row">
                <div class="col-sm-3"><%= link_to 'Show', old ,:class =>"btn btn-primary btn-sm"%></div>
                <div class="col-sm-3"><%= link_to 'Edit', edit_old_path(old),:class =>"btn btn-primary btn-sm" %></div>
                <div class="col-sm-3"><%= link_to 'Destroy', old,:class =>"btn btn-primary btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></div>
                <div class="col-sm-3"><a href="payment.html"><button type="button" class="btn btn-primary btn-sm">Payment</button></a></div>
              </div>
            </div>
            <div class="d-flex align-items-center justify-content-between rounded-pill bg-light px-3 py-2 mt-4">
              <p class="small mb-0"><i class="fa fa-picture-o mr-2"></i><span class="font-weight-bold">JPEG</span></p>
              <div class="badge badge-success px-3 rounded-pill font-weight-normal">Hot</div>
            </div>
          </div>
          <div class="extra content">
            <%= link_to line_items_url(:old_id => old.id), :method => :post do %>
              <div class="ui fluid labeled button" tabindex="0">
                <div class="ui red fluid button">
                  <i class="cart arrow down icon"></i> Add To Cart
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <% end %>
      <!-- End -->
    </div>
    <div class="py-5 text-right"><a href="#" class="btn btn-dark px-5 py-3 text-uppercase">Show me more</a></div>
  </div>
</div>
</body>
</html>

app/views/olds/new.html.erb
<h1>New Old</h1>

<%= render 'form', old: @old %>

<%= link_to 'Back', olds_path %>

app/views/olds/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Image:</strong>
  <%= image_tag(@old.image, style: 'height:50%; width:50%;') if @old.image.attached? %></div>
</p>
<p>
  <strong>Name:</strong>
  <%= @old.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @old.company %>
</p>

<p>
  <strong>Price:</strong>
  <%= @old.price %>
</p>

<p>
  <strong>Modal:</strong>
  <%= @old.modal %>
</p>

<p>
  <strong>Seat:</strong>
  <%= @old.seat %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @old.owner %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @old.desc %>
</p>

<%= link_to 'Edit', edit_old_path(@old) %> |
<%= link_to 'Back', olds_path %>